apiVersion: v1
kind: Namespace
metadata:
  name: test-workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: test-workload
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["sleep", "36000"]
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: false
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
